[general]
check_delay = 10

[email]
base_url = "https://connect.mailerlite.com/api"
api_key = "xxx"
ar_group_id = "xxx"
batch_size = 100

[database]
name = "goerli"
connection_string = "xxxxxx"

[watchtower]
enabled = true
endpoint = "https://api.watchtower.starknet.id/service/add_message"
app_id = "XXXXXXXXXXXXXXXXX"
token = "XXXXXXXXXXXXXXXXX"
[watchtower.types]
info = "goerli/info"
warning = "goerli/warning"
severe = "goerli/severe"
